import Link from "next/link";

// The disclaimer stack here is the substantive part: Osprey produces
// investment ANALYSIS, not brokerage/advisory services. Staying on the
// "informational analytics" side of NRS 645 (brokerage) and the Advisers Act
// (securities — direct real estate isn't one) is what keeps the product
// unlicensed-but-lawful, so §3 and §4 are load-bearing, not boilerplate.

/** Fixed; hand-edited on material change. See the note in privacy/page.tsx. */
const EFFECTIVE_DATE = "July 21, 2026";

export const metadata = {
  title: "Terms of Service — Osprey",
};

export default function TermsOfService() {
  return (
    <main className="mx-auto w-full max-w-3xl flex-1 bg-black px-6 py-20 text-white">
      <Link href="/" className="text-sm text-white/50 underline hover:text-white/80">
        &larr; Back to Osprey
      </Link>

      <h1 className="mt-6 text-3xl font-semibold tracking-tight">Terms of Service</h1>
      <p className="mt-2 text-sm text-white/40">Effective date: {EFFECTIVE_DATE}</p>

      <div className="mt-10 space-y-8 leading-7 text-white/80">
        <section>
          <h2 className="text-lg font-semibold text-white">1. Agreement</h2>
          <p className="mt-2">
            These Terms of Service govern your access to and use of the Osprey website, dashboard,
            and Telegram bot (together, the &quot;Service&quot;). By creating an account, joining the
            waitlist, or using the Service, you agree to these terms. If you do not agree, do not use
            the Service. Our{" "}
            <Link href="/privacy" className="underline hover:text-white">
              Privacy Policy
            </Link>{" "}
            is part of these terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">2. What Osprey is</h2>
          <p className="mt-2">
            Osprey is a software tool that gathers real-estate listing data, applies underwriting
            calculations using criteria and financing assumptions you configure, and reports the
            results to you. It is an analytics and information product for your own use.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">
            3. Not advice — please read this carefully
          </h2>
          <p className="mt-2">
            <span className="text-white">
              Osprey is provided for informational and educational purposes only. It is not
              investment, legal, tax, financial, accounting, appraisal, or real-estate brokerage
              advice, and no fiduciary or advisory relationship is created by your use of it.
            </span>
          </p>
          <p className="mt-2">
            Osprey is not a licensed real-estate broker or salesperson, mortgage lender or broker,
            appraiser, investment adviser, or tax professional. We do not represent you in any
            transaction, negotiate on your behalf, or recommend that you buy, sell, or finance any
            particular property. Any decision you make is yours alone. Consult appropriately licensed
            professionals before acting.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">4. Accuracy of data and estimates</h2>
          <p className="mt-2">
            Figures shown by the Service — including rent estimates, comparable properties, taxes,
            insurance, expenses, cash flow, cap rate, cash-on-cash return, projections, maximum-offer
            calculations, and payment-standard comparisons — are{" "}
            <span className="text-white">estimates</span> produced from third-party data and modeling
            assumptions. They may be inaccurate, incomplete, or out of date, and actual results will
            differ.
          </p>
          <p className="mt-2">
            Third-party listing and rent data is provided as-is and we do not independently verify
            it. Projections are hypothetical illustrations based on assumptions that will not hold
            exactly; past or projected performance does not guarantee future results. Some responses
            are generated by artificial intelligence and may contain errors. Verify every material
            figure independently — including rents, taxes, insurance, condition, occupancy, zoning,
            and title — before making any offer or financial commitment.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">5. Your account</h2>
          <p className="mt-2">
            You must provide accurate information, be at least 18 years old, and keep your credentials
            confidential. You are responsible for activity under your account. Access is currently
            invite-only, and we may decline, suspend, or terminate accounts at our discretion. Notify
            us promptly at{" "}
            <a href="mailto:hello@getosprey.ai" className="underline hover:text-white">
              hello@getosprey.ai
            </a>{" "}
            if you believe your account has been compromised.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">6. Acceptable use</h2>
          <p className="mt-2">You agree not to:</p>
          <ul className="mt-2 list-disc space-y-1 pl-6">
            <li>Scrape, crawl, resell, or systematically extract data or output from the Service</li>
            <li>Attempt to gain unauthorized access to the Service, other accounts, or our systems</li>
            <li>Interfere with, overload, or disrupt the Service or circumvent usage limits</li>
            <li>Reverse engineer the Service except where that restriction is unenforceable by law</li>
            <li>Use the Service unlawfully, including in violation of fair housing, lending, or
              anti-discrimination laws</li>
            <li>Misrepresent Osprey output as a licensed appraisal, broker price opinion, or
              professional advice</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">7. Share links and your content</h2>
          <p className="mt-2">
            You retain ownership of the information you enter. You grant us a limited license to
            process it in order to operate and improve the Service.
          </p>
          <p className="mt-2">
            When you create a share link, you make that analysis available to anyone holding the
            link, displayed with your name as the preparer. You are responsible for who you share it
            with and for any representations you make about it. You can revoke a link at any time
            from the property page.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">8. Our intellectual property</h2>
          <p className="mt-2">
            The Service, including its software, underwriting engine, interface, and branding, is
            owned by Osprey and protected by intellectual property laws. These terms grant you a
            limited, non-exclusive, non-transferable, revocable right to use the Service for your own
            real-estate analysis, and no other rights.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">9. Availability and changes</h2>
          <p className="mt-2">
            The Service is under active development and is provided on an early-access basis. We may
            add, change, suspend, or discontinue features at any time, and availability, scanning
            frequency, coverage, and message delivery are not guaranteed. We may impose usage limits.
            Some features depend on third-party services we do not control.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">10. Disclaimer of warranties</h2>
          <p className="mt-2">
            THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE,&quot; WITHOUT WARRANTIES
            OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
            FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, AND ANY WARRANTY AS TO ACCURACY,
            RELIABILITY, TIMELINESS, OR COMPLETENESS OF DATA OR OUTPUT. WE DO NOT WARRANT THAT THE
            SERVICE WILL BE UNINTERRUPTED, SECURE, OR ERROR-FREE. Some jurisdictions do not allow
            certain warranty exclusions, so parts of this section may not apply to you.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">11. Limitation of liability</h2>
          <p className="mt-2">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, OSPREY AND ITS OWNERS, OPERATORS, AND SUPPLIERS
            WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR
            PUNITIVE DAMAGES, OR FOR ANY LOST PROFITS, LOST INVESTMENT RETURNS, LOST OPPORTUNITIES,
            DIMINUTION IN VALUE, OR LOSS OF DATA, ARISING OUT OF OR RELATING TO YOUR USE OF OR
            INABILITY TO USE THE SERVICE OR ANY DECISION YOU MAKE BASED ON IT, EVEN IF ADVISED OF THE
            POSSIBILITY OF SUCH DAMAGES.
          </p>
          <p className="mt-2">
            OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS RELATING TO THE SERVICE WILL NOT EXCEED THE
            GREATER OF (A) THE AMOUNTS YOU PAID US FOR THE SERVICE IN THE TWELVE MONTHS BEFORE THE
            CLAIM AROSE, OR (B) ONE HUNDRED U.S. DOLLARS ($100). Some jurisdictions do not allow
            certain limitations, so parts of this section may not apply to you.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">12. Indemnification</h2>
          <p className="mt-2">
            You agree to indemnify and hold harmless Osprey and its owners and operators from claims,
            damages, losses, and reasonable legal fees arising out of your use of the Service, your
            violation of these terms or applicable law, or content you share through the Service,
            including through share links.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">13. Termination</h2>
          <p className="mt-2">
            You may stop using the Service and request account deletion at any time by emailing{" "}
            <a href="mailto:privacy@getosprey.ai" className="underline hover:text-white">
              privacy@getosprey.ai
            </a>
            . We may suspend or terminate access if you violate these terms or to protect the Service
            or other users. Sections that by their nature should survive termination — including
            Sections 3, 4, 8, 10, 11, 12, and 14 — will survive.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">14. Governing law and disputes</h2>
          <p className="mt-2">
            These terms are governed by the laws of the State of Nevada, without regard to its
            conflict-of-laws rules. You and Osprey agree that any dispute arising out of or relating
            to these terms or the Service will be brought exclusively in the state or federal courts
            located in Clark County, Nevada, and both parties consent to personal jurisdiction there.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">15. General</h2>
          <p className="mt-2">
            If any provision of these terms is held unenforceable, the rest remains in effect. Our
            failure to enforce a provision is not a waiver of it. You may not assign these terms
            without our consent; we may assign them in connection with a merger, acquisition, or sale
            of assets. These terms and the Privacy Policy are the entire agreement between you and
            Osprey regarding the Service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">16. Changes to these terms</h2>
          <p className="mt-2">
            We may update these terms. We will post the revised version here and update the effective
            date, and for material changes we will provide prominent notice before they take effect.
            Continuing to use the Service after a change takes effect means you accept the revised
            terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-white">17. Contact</h2>
          <p className="mt-2">
            Questions about these terms:{" "}
            <a href="mailto:hello@getosprey.ai" className="underline hover:text-white">
              hello@getosprey.ai
            </a>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
